USER_ROLE_NAME: str = "user"
ASSISTANT_ROLE_NAME: str = "assistant"
NOTEBOOK_DEFAULT_NAME: str = "Untitled Notebook"
SOURCE_DEFAULT_NAME: str = "Untitled Document"
NOTE_DEFAULT_TITLE: str = "Untitled Note"

MAX_NOTEBOOK_NAME_LEN = 100
MAX_DESCRIPTION_LEN = 300
MAX_FILENAME_LEN = 200
MAX_NOTE_TITLE_LEN = 150
MAX_SOURCE_SUMMARY_LEN = 1000
MAX_SUGGESTED_QUESTION_LEN = 300